// app/api/roadmaps/generate/route.ts

import { NextRequest, NextResponse } from "next/server";
import { auth, currentUser } from "@clerk/nextjs/server"; // Updated: Added currentUser
import { z } from "zod";
import { getGeminiFlashModel } from "@/lib/gemini";
import { runNeo4jQuery } from "@/lib/neo4j";
import { createClient } from "@supabase/supabase-js";

// ── 1. VALIDATION SCHEMAS ───────────────────────────────────────────────────

const RequestSchema = z.object({
  targetRole: z.string().min(1),
  skillGaps: z.array(z.string()).min(1),
});

const RoadmapOutputSchema = z.object({
  title: z.string(),
  description: z.string(),
  estimatedWeeks: z.number(),
  nodes: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      description: z.string(),
      level: z.enum(["beginner", "intermediate", "advanced"]),
      estimatedDays: z.number(),
      resources: z.array(
        z.object({
          title: z.string(),
          url: z.string(),
          type: z.enum(["article", "video", "course", "documentation"]),
        })
      ),
    })
  ),
});

// ── 2. GRAPH DATABASE HELPER ────────────────────────────────────────────────

async function getSkillPathFromNeo4j(
  targetRole: string,
  skillGaps: string[]
): Promise<string[]> {
  try {
    return await runNeo4jQuery(async (session) => {
      const result = await session.run(
        `
        MATCH (r:Role {name: $targetRole})-[:REQUIRES]->(s:Skill)
        WHERE s.name IN $skillGaps OR s.category IN $skillGaps
        RETURN s.name AS skill
        ORDER BY s.level
        LIMIT 20
        `,
        { targetRole, skillGaps }
      );

      if (result.records.length > 0) {
        return result.records.map((r) => r.get("skill") as string);
      }
      return skillGaps;
    });
  } catch (error) {
    console.warn("[/api/roadmaps/generate] Neo4j Fallback Mode:", error);
    return skillGaps;
  }
}

// ── 3. SYSTEM PROMPT CONSTRUCT ──────────────────────────────────────────────

function buildPrompt(targetRole: string, orderedSkills: string[]): string {
  return `
You are an expert technical curriculum designer.
Generate a comprehensive, structural preparation roadmap for a student targeting the role: "${targetRole}".

The student needs to bridge these specific skill gaps (ordered by priority): ${orderedSkills.join(", ")}.

CRITICAL: You must output ONLY a valid, raw JSON object. Do NOT wrap it in markdown code blocks (no \`\`\`json blocks), and provide no pre-text or post-text explanation.

The JSON response must precisely follow this structure:
{
  "title": "String - Title of the roadmap",
  "description": "String - High level summary statement",
  "estimatedWeeks": 8,
  "nodes": [
    {
      "id": "string-kebab-case-id",
      "name": "String - Specific Skill Name",
      "description": "String - What the student needs to learn and focus on",
      "level": "beginner", 
      "estimatedDays": 5,
      "resources": [
        {
          "title": "String - Resource Name",
          "url": "String - Valid reference URL",
          "type": "documentation"
        }
      ]
    }
  ]
}

Note: Valid values for 'level' are: "beginner" | "intermediate" | "advanced".
Valid values for resource 'type' are: "article" | "video" | "course" | "documentation".
Provide 2-3 realistic resource references per node.
`.trim();
}

// ── 4. APIRoute ENDPOINT HANDLER ─────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    console.log("=========================================");
    console.log("🚀 ROUTE TRIGGERED: EXECUTING LATEST CODE");
    console.log("=========================================");

    // A. Clerk Authentication & Dynamic RLS Token Extraction
    const { userId, getToken } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized access token" }, { status: 401 });
    }

    // Fetch full account details directly from Clerk's backend core layer
    const clerkUser = await currentUser();

    // Fetch the specialized JWT token generated by Clerk specifically for Supabase RLS handshakes
    const supabaseToken = await getToken({ template: "supabase" });

    // Initialize an authenticated Supabase instance representing this explicit user context
    const authenticatedSupabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${supabaseToken}`,
          },
        },
      }
    );

    // B. Validate Incoming Request Structure
    const jsonBody = await request.json();
    const { targetRole, skillGaps } = RequestSchema.parse(jsonBody);

    // ── INTEGRATED: LAZY ONBOARDING STEP WITH ERROR VERIFICATION ────────────
    const { data: userCheck } = await authenticatedSupabase
      .from("users")
      .select("id")
      .eq("id", userId)
      .single();

    if (!userCheck) {
      console.log(`👤 Synchronizing profile row data for user: ${userId}`);
      
      const emailAddress = clerkUser?.emailAddresses[0]?.emailAddress || "developer@student.com";
      const userFullName = `${clerkUser?.firstName || ""} ${clerkUser?.lastName || ""}`.trim() || "Developer Student";

      const { error: onboardingError } = await authenticatedSupabase
        .from("users")
        .insert({ 
          id: userId,
          email: emailAddress,        // Fulfills required 'email' column constraint
          full_name: userFullName,    // Fulfills required 'full_name' column constraint
        });

      if (onboardingError) {
        console.error("❌ CRITICAL: USERS TABLE PROFILE WRITE FAILURE:", onboardingError);
        return NextResponse.json({ error: "Failed to allocate account profile row structure", details: onboardingError }, { status: 500 });
      }
      console.log("✅ User profile successfully written to Supabase under RLS validation!");
    }
    // ────────────────────────────────────────────────────────────────────────

    // C. Resolve Skill Nodes ordering from Graph Layer
    const orderedSkills = await getSkillPathFromNeo4j(targetRole, skillGaps);

    // ── D. Fetch Structural Data from Gemini Flash ───────────────────────────
    let roadmapData;
    try {
      const model = getGeminiFlashModel();
      
      const result = await model.generateContent({
        contents: [
          { 
            role: "user", 
            parts: [{ text: buildPrompt(targetRole, skillGaps) }] 
          }
        ],
        generationConfig: {
          responseMimeType: "application/json",
        },
      });
      
      const responseText = result.response.text().trim();
      const cleanJsonString = responseText.replace(/^```json\s*|```$/gi, "").trim();
      
      roadmapData = RoadmapOutputSchema.parse(JSON.parse(cleanJsonString));
    } catch (error: any) {
      console.warn("[/api/roadmaps/generate] Gemini Limit Hit or Error. Deploying Mock Fallback Architecture.", error.message);

      roadmapData = {
        title: `${targetRole} Preparation Path`,
        description: `Accelerated curriculum focusing on your core target areas: ${skillGaps.join(", ")}.`,
        estimatedWeeks: 6,
        nodes: [
          {
            id: "core-foundations",
            name: `Mastering ${skillGaps[0] || "Target Concepts"}`,
            description: "Deep dive into structural architecture, debugging workflows, and optimization paradigms.",
            level: "beginner" as const,
            estimatedDays: 5,
            resources: [
              {
                title: "Official Developer Documentation",
                url: "https://developer.mozilla.org/en-US/",
                type: "documentation" as const
              },
              {
                title: "In-Depth Video Guide",
                url: "https://youtube.com",
                type: "video" as const
              }
            ]
          },
          {
            id: "advanced-integration",
            name: `Advanced ${skillGaps[1] || "System Building"}`,
            description: "Implementing complex state patterns, data handling rules, and handling interface edge cases.",
            level: "intermediate" as const,
            estimatedDays: 7,
            resources: [
              {
                title: "Production Integration Playbook",
                url: "https://react.dev",
                type: "article" as const
              }
            ]
          }
        ]
      };
    }

    // E. Save Parent Roadmap Record to Supabase using the RLS-Authenticated Client
    const { data: roadmap, error: roadmapError } = await authenticatedSupabase
      .from("roadmaps")
      .insert({
        user_id: userId,
        title: roadmapData.title,
        description: roadmapData.description,
        target_role: targetRole,
        estimated_weeks: roadmapData.estimatedWeeks,
      })
      .select("id")
      .single();

    if (roadmapError || !roadmap) {
      console.error("[/api/roadmaps/generate] Supabase master insert error:", roadmapError);
      return NextResponse.json({ error: "Failed to allocate master roadmap entity" }, { status: 500 });
    }

    // ── F. Transform and Save Child Skill Nodes to 'tasks' Table ──────────────
    const nodeRows = roadmapData.nodes.map((node, index) => ({
      roadmap_id: roadmap.id,
      title: node.name,        
      description: node.description,
      status: index === 0 ? "in_progress" : "todo",
    }));

    const { error: nodesError } = await authenticatedSupabase
      .from("tasks")
      .insert(nodeRows);

    if (nodesError) {
      console.error("[/api/roadmaps/generate] Supabase child tasks insert error:", nodesError);
    }

    // G. Hand clean execution bundle back to the client-side UI
    return NextResponse.json({
      roadmap: {
        id: roadmap.id,
        ...roadmapData,
      },
    }, { status: 201 });

  } catch (error) {
    console.error("[/api/roadmaps/generate] Server processing error:", error);
    return NextResponse.json({ error: "Internal Server Processing Error" }, { status: 500 });
  }
}